# version format
version: 0.2.0.{build}

environment:
  powershellgallery_apikey:
    secure: mnc2Qk/sxVmJ1MXKzQMdNdA2RJYuf5/wZLchXz6cALTVuO9Y8alJf1mz+sa8+hMz
    
# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# build cache to preserve files/folders between builds
cache:
  - packages

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore
  
build:
  parallel: true                          # enable MSBuild parallel builds
  project: Elasticsearch.Powershell.sln   # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages

#after_build:
#  - ps: .\generate-doc.ps1
  
#before_test:
#  - ps: Start-FileDownload 'https://github.com/gigi81/elk-windows-installer/releases/download/v1.0.16/elk-x64-1.0.16.exe'
#  - elk-x64-1.0.16.exe /S /D=C:\Elk
  
test: off

deploy_script:
  - ps: .\deploy.ps1
